version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/capes-backend"
    schedule:
      interval: "daily"
    reviewers:
      - "PyrrhaDevs"
    labels:
      - "type: dependencies"
      - "area: backend"

  - package-ecosystem: "npm"
    directory: "/capes-frontend"
    schedule:
      interval: "daily"
    reviewers:
      - "PyrrhaDevs"
    labels:
      - "type: dependencies"
      - "area: frontend"