name: "backend"

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "capes-frontend/**"

jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v2"
        with:
          fetch-depth: 1
      - uses: "actions/setup-java@v1"
        with:
          java-version: 11
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build test --stacktrace
          gradle-version: current