name: "frontend"

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "capes-backend/**"

jobs:
  frontend:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v2"
        with:
          fetch-depth: 1
      - id: "yarn-cache-dir"
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: node_modules/
          key: ${{ runner.os }}-yarn-${{ hashFiles('./') }}